@Restaurants.API_HostAddress = http://localhost:5086

GET {{Restaurants.API_HostAddress}}/api/restaurants/

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Yamporage",
  "Description": "HeavyFood",
  "Category": "Locals",
  "HasDelivery": true,
  "ContactEmail" : "info@test.com",
  "ContactNumber": "91140633525",
  "City": "Ikeja",
  "Street": "Adeniyi-Jones",
  "PostalCode":"88-889"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5



###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "Name": "Eba",
  "Description": "Cassava",
  "HasDelivery": true
}

### //for Dishes

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{ "Name": "Hot Chicken Eba",
  "Description": "ggggggggggggggg",
  "Price":15
     
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/10/dishes

### //GetDishes by Id in Restaurant
GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/3

### //DeleteDishes by Id in Restaurant
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes/3

###
//For User
POST {{Restaurants.API_HostAddress}}/register
Content-Type: application/json

{
  "email" : "test@mail",
  "password" : "Testman1!"
}

###
//For User
POST {{Restaurants.API_HostAddress}}/login
Content-Type: application/json

{
  "email" : "test@mail",
  "password" : "Testman1!"
}
